MainApp/MainApp/Controllers/EntryController.cs
using Microsoft.AspNetCore.Mvc;
using MainApp.Services;
using MainApp.Models;

namespace MainApp.Controllers
{
    // Controller for managing user and staff registrations and logins
    public class EntryController : Controller
    {
        // Data context for users and crew
        private UserContext data;
        // Logger for exceptions
        private ILogger<AuthService> logger;
        private AuthService authService;
        private CookieService cookieService;

        public EntryController(UserContext _db , ILogger<AuthService> _logger)
        {
            data = _db;
            logger = _logger;
        }



        // Account registration
        [HttpGet]
        public IActionResult UserRegistration()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UserRegistration(CreateUserModel newUser)
        {
            authService = new AuthService(data, logger, HttpContext);

            if (ModelState.IsValid)
            {
                if (authService.AvailabilityCheck(newUser.Login))
                {
                    await authService.AddUserAsync(newUser.Login, newUser.Password);
                    return RedirectToAction("Study","Page");
                }
                else
                {
                    ViewBag.Error = "Пользователь с таким логином уже существует";
                    return View(newUser);
                }
            }

            return View(newUser);
        }



        // Account login
        [HttpGet]
        public IActionResult UserLogin()
        {
            cookieService = new CookieService(HttpContext);

            if (cookieService.GetUserInfo().Login != null)
            {
                return RedirectToAction("Study","Page");
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UserLogin(User user, bool remember)
        {
            authService = new AuthService(data, logger, HttpContext);

            if (ModelState.IsValid)
            {
                if (await authService.UserAuthenticationAsync(user.Login, user.Password))
                {
                    await authService.UserAuthorizationAsync(user.Login, remember);
                    return RedirectToAction("Study","Page");
                }
                else
                {
                    ViewBag.Error = "Логин или пароль неверны!";
                    return View(user);
                }
            }

            return View(user);
        }



        public async Task<IActionResult> Logout()
        {
            cookieService = new CookieService(HttpContext);
            await cookieService.LogoutAsync();
            return RedirectToAction("Welcome","Page");
        }




        [HttpGet]
        public IActionResult CrewLogin()
        {
            cookieService = new CookieService(HttpContext);

            switch (cookieService.GetUserInfo().Role) 
            {
                case "admin" or "editor": return RedirectToAction("ViewParts","Part", new { parentId=0, parentName="Секции", table="onload" });
                case "user": return RedirectToAction("Study", "Page");
                case "null": return View();
            }

            return null;
        }

        [HttpPost]
        public async Task<IActionResult> CrewLogin(Admin admin)
        {
            authService = new AuthService(data, logger, HttpContext);

            if (ModelState.IsValid)
            {
                if (await authService.AdmAuthenticationAsync(admin.Login, admin.Password) 
                || await authService.EdAuthenticationAsync(admin.Login, admin.Password))
                {
                    return RedirectToAction("ViewParts","Part", new { parentId=0, parentName="Секции", table="onload" });
                }

                ViewBag.Error = "Логин или пароль неверны!";
                return View(admin);
            }

            return View(admin);
        }
    }
}

MainApp/MainApp/Controllers/PageController.cs
using Microsoft.AspNetCore.Mvc;

namespace MainApp.Controllers
{
    // Controller to manage tutorial pages
    public class PageController : Controller
    {
        public IActionResult Welcome()
        {
            return View();
        }

        public IActionResult Study()
        {
            return View();
        }    

        public IActionResult ViewProfile()
        {
            return View();
        }

        [Route("/error/{statusCode}")]
        public IActionResult Error(int statusCode)
        {
            return View(statusCode);
        }
    }
}

MainApp/MainApp/Controllers/PartController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using MainApp.Services;
using MainApp.Models;

namespace MainApp.Controllers
{
    // Controller to manage tutorial parts 
    [Authorize(Roles = "admin, editor")]
    public class PartController : Controller
    {
        // Data context for parts
        private TopicsContext data;
        // Logger for exceptions
        private ILogger<PartsService> logger;
        private PartsService partService;

        public PartController(TopicsContext _db, ILogger<PartsService> _logger)
        {
            data = _db;
            logger = _logger;  
        }



        [HttpGet]
        public async Task<IActionResult> ViewParts(int parentId, string table)
        {
            partService = new PartsService(data, logger);

            if(parentId==0 && table==null)
            {
                table = "onload";
            }

            var parts = await partService.GetPartsAsync(parentId, table);
            var parent = await partService.GetPartAsync(parentId, table);
            if(parent == null)
            {
                return RedirectToAction("Error", "Page");
            }

            ViewBag.ParentId = parentId;
            ViewBag.ParentName = parent.Title;
            ViewBag.Table = table;
            if(table != "onload")
            {
                ViewBag.Parent = await partService.GetPartAsync(parent.ParentId, parent.ParentTable); 
            }

            return View(parts);
        }

        [HttpGet]
        public async Task<IActionResult> ViewPost(int postId)
        {
            partService = new PartsService(data, logger);

            var post = (Post)await partService.GetPartAsync(postId, "post");
            if (post == null)
            {
                return RedirectToAction("Error", "Page");
            }

            ViewBag.Content = await partService.GetContentAsync(post.ContentId);
            return View(post);          
        }



        [HttpGet]
        public async Task<IActionResult> AddPart(int parentId, string table)
        {
            partService = new PartsService(data, logger);

            var parentName = (await partService.GetPartAsync(parentId, table)).Title;    
            return View(new GeneralPart { Id = parentId, Title = parentName, Table = table });
        }

        [HttpPost]
        public async Task<IActionResult> AddPart(
            int parentId, 
            string parentName,
            string table, 
            string partName, 
            string content)
        {
            partService = new PartsService(data, logger);

            if(partName == null)
            {
                return View(new GeneralPart { Id = parentId, Title = parentName, Table = table });
            }
            if (await partService.AddPartAsync(parentId, partName, content, table))
            {
                return RedirectToAction("ViewParts", new { parentId, table });
            }

             return RedirectToAction("AddPart", new { parentId, table });
        }



        [HttpGet]
        public async Task<IActionResult> UpdatePart(int partId, string table)
        {
            partService = new PartsService(data, logger);

            var part = await partService.GetPartAsync(partId, table);
            if (part == null)
            {
                return RedirectToAction("Error", "Page");
            }

            if (table != "section")
            {
                ViewBag.Parents = await partService.GetPartsParentsAsync(partId, table);  
                if(table == "post")
                {
                    ViewBag.Content = await partService.GetContentAsync(((Post)part).ContentId);
                }            
            }

            return View(part);
        }

        [HttpPost]
        public async Task<IActionResult> UpdatePart(
            int partId, 
            string newName, 
            string newContent, 
            string table, 
            int newParentId,

            int parentId,  
            string parentTable)
        {
            partService = new PartsService(data, logger);

            if (await partService.UpdatePartAsync(partId, newParentId, newName, newContent, table))
            {           
                return RedirectToAction("ViewParts", new { parentId, table = parentTable });
            }

            return RedirectToAction("UpdatePart", new { partId, table });
        }



        [HttpDelete]
        [Route("/api/part/remove/{table}&{partId:int}")]
        public async Task<IActionResult> DeletePart(int partId, string table)
        {
            partService = new PartsService(data, logger);

            var id = await partService.RemovePartAsync(partId, table);
            return Json(id);
        }
    }
}

MainApp/MainApp/Views/Layout/EntryLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="shortcut icon" href=~/img/favicon.ico/>
    <link rel="stylesheet" href=~/css/entrylayout.min.css/>
</head>
<body>
    <main class="content">      
        <div class="content__wrapper">
            <div class="content__brand">
                <a asp-controller="Page" asp-action="Welcome">
                    <img src="~/img/favicon.png" class="content-brand__logo">
                </a>
            </div>

            <div class="content__head">               
                @if (IsSectionDefined("Header"))
                {
                    @RenderSection("Header")
                }
            </div>

            <div>
                @RenderBody()
            </div>
        </div>
    </main>
</body>
</html>

MainApp/MainApp/Views/Layout/MainLayout.cshtml
@using System.Security.Claims;
@using Microsoft.AspNetCore.Http;

@functions{
    public string GetUserRole()
    {
        var roleCookie = Context.User.FindFirst(ClaimsIdentity.DefaultRoleClaimType); 
        if (roleCookie != null)
        {
            return roleCookie.Value;
        }

        var roleSession = Context.Session.GetString("role"); 
        if (roleSession != null)
        {
            return roleSession;
        }
        return null;
    }
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="shortcut icon" href=~/img/favicon.ico/>
    <link rel="stylesheet" href=~/css/mainlayout.min.css/> 
</head>
<body>
    <header>      
        <div class="head">
            <nav class="head__nav">
                <ul class="head__menu">
                    @if (@GetUserRole() == "admin" || @GetUserRole() == "editor")
                    {    
                        <li class="head__item"><a asp-controller="Part" asp-action="ViewParts">Управление</a></li>
                        <li class="head__item"><a asp-controller="#" asp-action="#">Учебник</a></li>
                    }
                    else
                    {
                        <li class="head__item"><a asp-controller="Page" asp-action="Study">Учащимся</a></li>
                        <li class="head__item"><a asp-controller="#" asp-action="#">Вакансии</a></li>
                        <li class="head__item"><a asp-controller="#" asp-action="#">О Нас</a></li>
                    }
                </ul>                
            </nav>

            <div class="head__face">
                <div class="head__brand">
                    <a asp-controller="Page" asp-action="Welcome">
                        <img src="~/img/favicon.png" class="head-brand__logo">
                        <h2 class="head-brand__name">Tutorial Book</h2>
                    </a>
                </div>
            </div>
            
            <div class="head__account">
                @if (@GetUserRole() == null)
                {
                    <a asp-controller="Entry" asp-action="UserLogin">Войти</a>
                    <a asp-controller="Entry" asp-action="UserRegistration">Регистрация</a>
                }
                else
                {
                    <a asp-controller="Page" asp-action="ViewProfile">Аккаунт</a>
                    <a asp-controller="Entry" asp-action="Logout">Выйти</a>
                } 
            </div>
        </div>
    </header>

    <main class="">
        @RenderBody()
    </main>

    <footer>
        <div class="bottom">
            <article class="bottom-main">
                <div class="bottom__we">
                    <a asp-controller="Page" asp-action="Welcome">
                        <img src="~/img/favicon.png" class="bottom-we__logo">
                    </a>
                    <span> Copyright © 2022 LeoIsak, Inc. </span>
                </div>
                
                <ul class="bottom__info">
                    <li class="bottom-info__item"><a asp-controller="#" asp-action="#">Правообладателям</a></li>
                    <li class="bottom-info__item"><a asp-controller="#" asp-action="#">Конфидециальность</a></li>
                    <li class="bottom-info__item"><a asp-controller="#" asp-action="#">Связь с нами</a></li>
                    <li class="bottom-info__item"><a asp-controller="Entry" asp-action="CrewLogin">Сотрудникам</a></li>
                </ul>
            </div>
        </div>
    </footer>
</body>
</html>