MainApp/MainApp/Models/Parts/Chapter.cs
namespace MainApp.Models
{
    public class Chapter : GeneralPart
    {
    }
}

MainApp/MainApp/Models/Parts/ContentModel.cs
using System.ComponentModel.DataAnnotations;

namespace MainApp.Models
{
    // Model for posts content
    public class ContentModel
    {
        [Key]
        public int Id { get; set; }
        public string? Content { get; set; }
    }
}

MainApp/MainApp/Models/Parts/GeneralPart.cs
using System.ComponentModel.DataAnnotations;

namespace MainApp.Models
{
    // Section -> Subsection -> Chapter -> Subchapter -> Post

    // Model for Part, which is used to merge all parts into one
    public class GeneralPart
    {
        [Key]
        public int Id { get; set; }
        public string? Title { get; set; }
        public string Table { get; set; } = "";
        public DateTime? CreatedDate { get; set; }

        public int? ParentId { get; set; }
        public string? ParentTable { get; set; }
    }
}

MainApp/MainApp/Models/Parts/Post.cs
namespace MainApp.Models
{
    // Section -> Subsection -> Chapter -> Subchapter -> POST

    // Model for Post
    public class Post : GeneralPart
    {
        public int? ContentId { get; set; }
    }
}

MainApp/MainApp/Models/Parts/Section.cs
namespace MainApp.Models
{
    public class Section : GeneralPart
    {
    }
}

MainApp/MainApp/Models/Parts/Subchapter.cs
namespace MainApp.Models
{
    public class Subchapter : GeneralPart
    {
    }
}

MainApp/MainApp/Models/Parts/Subsection.cs
namespace MainApp.Models
{
    public class Subsection : GeneralPart
    {
    }
}

MainApp/MainApp/Controllers/PartController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using MainApp.Services;
using MainApp.Models;

namespace MainApp.Controllers
{
    // Controller to manage tutorial parts 
    [Authorize(Roles = "admin, editor")]
    public class PartController : Controller
    {
        // Data context for parts
        private TopicsContext data;
        // Logger for exceptions
        private ILogger<PartsService> logger;
        private PartsService partService;

        public PartController(TopicsContext _db, ILogger<PartsService> _logger)
        {
            data = _db;
            logger = _logger;  
        }



        [HttpGet]
        public async Task<IActionResult> ViewParts(int parentId, string table)
        {
            partService = new PartsService(data, logger);

            if(parentId==0 && table==null)
            {
                table = "onload";
            }

            var parts = await partService.GetPartsAsync(parentId, table);
            var parent = await partService.GetPartAsync(parentId, table);
            if(parent == null)
            {
                return RedirectToAction("Error", "Page");
            }

            ViewBag.ParentId = parentId;
            ViewBag.ParentName = parent.Title;
            ViewBag.Table = table;
            if(table != "onload")
            {
                ViewBag.Parent = await partService.GetPartAsync(parent.ParentId, parent.ParentTable); 
            }

            return View(parts);
        }

        [HttpGet]
        public async Task<IActionResult> ViewPost(int postId)
        {
            partService = new PartsService(data, logger);

            var post = (Post)await partService.GetPartAsync(postId, "post");
            if (post == null)
            {
                return RedirectToAction("Error", "Page");
            }

            ViewBag.Content = await partService.GetContentAsync(post.ContentId);
            return View(post);          
        }



        [HttpGet]
        public async Task<IActionResult> AddPart(int parentId, string table)
        {
            partService = new PartsService(data, logger);

            var parentName = (await partService.GetPartAsync(parentId, table)).Title;    
            return View(new GeneralPart { Id = parentId, Title = parentName, Table = table });
        }

        [HttpPost]
        public async Task<IActionResult> AddPart(
            int parentId, 
            string parentName,
            string table, 
            string partName, 
            string content)
        {
            partService = new PartsService(data, logger);

            if(partName == null)
            {
                return View(new GeneralPart { Id = parentId, Title = parentName, Table = table });
            }
            if (await partService.AddPartAsync(parentId, partName, content, table))
            {
                return RedirectToAction("ViewParts", new { parentId, table });
            }

             return RedirectToAction("AddPart", new { parentId, table });
        }



        [HttpGet]
        public async Task<IActionResult> UpdatePart(int partId, string table)
        {
            partService = new PartsService(data, logger);

            var part = await partService.GetPartAsync(partId, table);
            if (part == null)
            {
                return RedirectToAction("Error", "Page");
            }

            if (table != "section")
            {
                ViewBag.Parents = await partService.GetPartsParentsAsync(partId, table);  
                if(table == "post")
                {
                    ViewBag.Content = await partService.GetContentAsync(((Post)part).ContentId);
                }            
            }

            return View(part);
        }

        [HttpPost]
        public async Task<IActionResult> UpdatePart(
            int partId, 
            string newName, 
            string newContent, 
            string table, 
            int newParentId,

            int parentId,  
            string parentTable)
        {
            partService = new PartsService(data, logger);

            if (await partService.UpdatePartAsync(partId, newParentId, newName, newContent, table))
            {           
                return RedirectToAction("ViewParts", new { parentId, table = parentTable });
            }

            return RedirectToAction("UpdatePart", new { partId, table });
        }



        [HttpDelete]
        [Route("/api/part/remove/{table}&{partId:int}")]
        public async Task<IActionResult> DeletePart(int partId, string table)
        {
            partService = new PartsService(data, logger);

            var id = await partService.RemovePartAsync(partId, table);
            return Json(id);
        }
    }
}

MainApp/MainApp/Views/Part/AddPart.cshtml
@model MainApp.Models.GeneralPart

@{
    ViewBag.Title = "Добавление компонента";
    Layout = "/Views/Layout/MainLayout.cshtml";
}

<link rel="stylesheet" href="~/css/update-addpart.min.css">

<div class="content__wrapper">
    <h2>Добавление компонента в<br>"@Model.Title"</h2>
    <span class="addform__main-error" id="">Такое название уже существует!</span>
    <form asp-controller="Part" asp-action="AddPart" method="post" class="addform">
        <div class="addform__main">           
            <label>Название компонента:</label><br>
            <input class="addform__main-input" type="text" name="partName" id="partName"
            oninput="ValidCheckAdd()">
            <span class="addform__main-error" id="validerror">Введите название!</span><br>

            @if(@Model.Table == "subchapter")
            {
                <label>Содержимое поста:</label><br>
                <textarea class="addform__main-textarea" wrap="hard" name="content" id="content">@ViewBag.Content</textarea><br>
            }

            <input name="parentId" value="@Model.Id" style="display: none;">     
            <input name="parentName" value="@Model.Title" style="display: none;">  
            <input name="table" value="@Model.Table" style="display: none;">

            <div class="addform__main-button">
                <input type="submit" value="Добавить" onclick="RemoveStorage()">
            </div>
        </div>
    </form>  
</div>

<script src="~/js/min/textstorage.min.js"></script>

MainApp/MainApp/Views/Part/UpdatePart.cshtml
@model MainApp.Models.GeneralPart

@{
    ViewBag.Title = "Изменение компонента";
    Layout = "/Views/Layout/MainLayout.cshtml";
}

<link rel="stylesheet" href="~/css/update-addpart.min.css">

<div class="content__wrapper">
    <h2>Изменение компонента<br>"@Model.Title"</h2>
    <span class="addform__main-error" id="validerror">Такое название уже существует!</span>
    <form asp-controller="Part" asp-action="UpdatePart" method="post" class="addform">
        <div class="addform__main">
            <label>Новое название: </label><br>
            <input class="addform__main-input" type="text" name="newName" id="newName" value="@Model.Title" 
            oninput="ValidCheckChange()">
            <span class="addform__main-error" id="validerror">Введите название!</span><br>

            @if(ViewBag.Parents != null && ViewBag.Parents.Count != 0)
            {
                <select class="addform__main-select" name="newParentId">
                    <option value="@Model.ParentId">По умолчанию</option>
                    @foreach (var parent in ViewBag.Parents)
                    {
                        <option value="@parent.Id">@parent.Title</option>
                    }
                </select><br>
            }

            @if(@Model.Table == "post")
            {
                <label>Новое cодержимое поста:</label><br>
                <textarea class="addform__main-textarea" wrap="hard" type="text"
                name="newContent" id="newContent">@ViewBag.Content</textarea><br>
            }

            <input name="partId" value="@Model.Id" style="display: none;">
            <input name="table" value="@Model.Table" style="display: none;">
            <input name="parentId" value="@Model.ParentId" style="display: none;">
            <input name="parentTable" value="@Model.ParentTable" style="display: none;">

            <div class="addform__main-button">
                <input type="submit" value="Изменить" onclick="RemoveStorage()">
            </div>
        </div>
    </form>
</div>

<script src="~/js/min/textstorage.min.js"></script>

MainApp/MainApp/Views/Part/ViewParts.cshtml
@model List<MainApp.Models.GeneralPart>

@{
    ViewBag.Title = "Управление";
    Layout = "/Views/Layout/MainLayout.cshtml";
}

@functions{
    public string TableName(string table, string parentName)
    {
        switch (table)
        {
            case "onload":
                return "Секции";
            case "section":
                return $"Подсекции в секции «{parentName}»";
            case "subsection":
                return $"Разделы в подсекции «{parentName}»";
            case "chapter":
                return $"Подразделы в разделе «{parentName}»";
            case "subchapter":
                return $"Посты в подразделе «{parentName}»";
        }
        return null;
    }
}

<link rel="stylesheet" href="~/css/viewparts.min.css">
<script src="~/js/min/api.min.js"></script>

<div class="content__wrapper">
    @await Html.PartialAsync("~/Views/Partial/CrewPanel.cshtml")
    <div class="content__main">
        <h2>@TableName(@ViewBag.Table, @ViewBag.ParentName)</h2>
        @if(@ViewBag.Table != "onload")
        {
            <h3 class="main__title">
                <a asp-controller="Part" asp-action="ViewParts"
                asp-route-parentId="@ViewBag.Parent.Id" asp-route-parentName="@ViewBag.Parent.Title" 
                asp-route-table="@ViewBag.Parent.Table">Вернуться назад</a> 
            </h3>
        }

        <table class="main__table">
            <thead class="main__table-hat">
                <tr class="main__table-row">
                    <th class="main__table-header"><h3>Название</h3></th>
                    <th class="main__table-header">
                        <h3>
                            <a asp-controller="Part" asp-action="AddPart" 
                            asp-route-parentId="@ViewBag.ParentId" asp-route-table="@ViewBag.Table">Добавить</a>                      
                        </h3>
                    </th>
                </tr>
            </thead>
            <tbody class="main__table-body">
                @if(Model.Count!=0)
                {
                    @foreach (var part in Model.OrderBy(p => p.Id))
                    {
                        <tr class="main__table-row" id="@part.Id">
                            <td class="main__table-data">@part.Title</td>
                            <td class="main__table-data">
                                @if(@ViewBag.Table == "subchapter")
                                {
                                    <a asp-controller="Part" asp-action="ViewPost" 
                                    asp-route-postId="@part.Id">Подробнее</a> 
                                }
                                else
                                {
                                    <a asp-controller="Part" asp-action="ViewParts" 
                                    asp-route-parentId="@part.Id" asp-route-parentName="@part.Title" 
                                    asp-route-table="@part.Table">Подробнее</a> 
                                }

                                <a asp-controller="Part" asp-action="UpdatePart" 
                                asp-route-partId="@part.Id"asp-route-table="@part.Table">Изменить</a> 

                                <a onclick="deletePart(@part.Id, '@ViewBag.Table')">Удалить</a>   
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr class="main__table-row" id="empty-table">
                        <td class="main__table-data" >
                            Ничего нет
                        </td>
                    </tr>
                }      
            </tbody>
        </table>
    </div>
</div>

MainApp/MainApp/Views/Part/ViewPost.cshtml
@model MainApp.Models.Post

@{
    ViewBag.Title = "Промотр поста";
    Layout = "/Views/Layout/MainLayout.cshtml";
}

<div>
    @ViewBag.Content
</div>